//
// Created by zraba on 14.10.2022.
//

#ifndef SATELLIT_A10_SRC_NET_CONFIG_H_
#define SATELLIT_A10_SRC_NET_CONFIG_H_

#define NET_INTERFACE_COUNT 4

#define NET_LOOPBACK_IF_SUPPORT ENABLED
#define TCP_SUPPORT ENABLED
#define UDP_SUPPORT ENABLED
#define RAW_SOCKET_SUPPORT ENABLED

#define DHCP_SERVER_SUPPORT ENABLED

#endif //SATELLIT_A10_SRC_NET_CONFIG_H_
